# Generated by Django 5.2.6 on 2025-09-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitmodel',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
